version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_server_db
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "YourStrong@Password123" # IMPORTANT: Change this to a strong password!
    volumes:
      - sqlserver_data:/var/opt/mssql # Persist data
    restart: always

volumes:
  sqlserver_data:
